http:
  routers:
    dsm:
      entryPoints:
        - websecure
      rule: "Host(`{{ env "DSM_EXTERNAL_DOMAIN" }}`)"
      service: dsm
    dsm-old:
      entryPoints:
        - websecure
      rule: "Host(`{{ env "DSM_OLD_EXTERNAL_DOMAIN" }}`)"
      service: dsm-old
    homeassistant:
      entryPoints:
        - websecure
      rule: "Host(`{{ env "HOMEASSISTANT_EXTERNAL_DOMAIN" }}`)"
      service: homeassistant
    ollama:
      entryPoints:
        - websecure
      rule: "Host(`{{ env "OLLAMA_EXTERNAL_DOMAIN" }}`)"
      service: ollama
    router:
      entryPoints:
        - websecure
      rule: "Host(`{{ env "ROUTER_EXTERNAL_DOMAIN" }}`)"
      service: router
  services:
    dsm:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{ env "DSM_URL" }}"
    dsm-old:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{ env "DSM_OLD_URL" }}"
    homeassistant:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{ env "HOMEASSISTANT_URL" }}"
    ollama:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{ env "OLLAMA_URL" }}"
    router:
      loadBalancer:
        passHostHeader: true
        servers:
        - url: "{{ env "ROUTER_URL" }}"
